### ISSUE TITLE
Uncaught SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by enricribas** [swenson/atom-jsonpp#4]
[Enter steps to reproduce below:]
Using this JSON, it crashes.

{"utf8"=>"✓", "authenticity_token"=>"5Ape0vboEKRUXsNnIqymAjq9bygnFMXJ6esrr4Fo9U3kDWFv8E42Lh4RnnNwjaGY9gn1rnkz2nF5PaeGlt/Ofw==", "embedded"=>"true", "opportunity_name"=>"Lostss-", "challenge"=>{"code"=>"", "salesforce_opp_id"=>"006d000000FcoVE", "challenge_type_id"=>"5", "prospect"=>"003d000001W1DH4AAN", "prospect_attributes"=>{"name"=>"Ryan Lost", "owner_id"=>"", "sfdc_contact_id"=>"003d000001W1DH4AAN", "company"=>"Lostss", "title"=>"tabb", "email"=>"ryan@lost.com", "phone"=>"777 777 7777"}, "match_info"=>{"1"=>{"values"=>"", "essential"=>"", "importance"=>"2"}, "2"=>{"values"=>"", "essential"=>"", "importance"=>"2"}, "3"=>{"values"=>"", "essential"=>"", "importance"=>"2"}}, "visibility_attributes"=>{"contact_ids"=>"", "end_at"=>"2015-03-16"}, "notes"=>"required notes"}, "reference_request"=>"true", "page"=>"1", "commit"=>"Sending..."}
1. Highlight the data
2. ctlr-alt-j

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: [jsonpp](https://github.com/swenson/atom-jsonpp) package, v0.0.6
### Stack Trace

Uncaught SyntaxError: Unexpected token =

```
At file:///Applications/Atom.app/Contents/Resources/app/static/index.html?loadSettings=%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3Anull%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.186.0%22%2C%22shellLoadTime%22%3A2008%2C%22initialPaths%22%3A%5B%5D%7D:1

SyntaxError: Unexpected token =
  at Object.parse (native)
  at Object.module.exports.compact (/Users/enric/.atom/packages/jsonpp/lib/jsonpp.coffee:38:37)
  at atom-workspace.<anonymous> (/Users/enric/.atom/packages/jsonpp/lib/jsonpp.coffee:12:63)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```
### Commands

```
     -1:39.7 editor:consolidate-selections (atom-text-editor.editor.mini)
  2x -1:39.7 AtomPair:hide views (atom-text-editor.editor.mini)
     -1:39.0 settings-view:open (atom-workspace.workspace.theme-one-dark-syntax.theme-atom-dark-ui.scrollbars-visible-always)
     -1:29.2 core:confirm (atom-text-editor.editor.mini)
     -1:00.1 editor:select-line (atom-text-editor.editor.is-focused)
     -0:59.8 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:56.2 core:confirm (atom-text-editor.editor.mini)
     -0:56.1 pretty-json:prettify (atom-text-editor.editor.is-focused)
     -0:52.3 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:49.2 core:move-down (atom-text-editor.editor.mini)
     -0:48.6 core:confirm (atom-text-editor.editor.mini)
     -0:48.6 pretty-json:sort-and-prettify (atom-text-editor.editor.is-focused)
     -0:45.9 settings-view:open (atom-text-editor.editor.is-focused)
     -0:34.8 core:confirm (atom-text-editor.editor.mini)
     -0:04.0 emmet:matching-pair (atom-text-editor.editor.is-focused)
     -0:01.5 jsonpp:compact (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "vim-mode",
      "autocomplete-plus"
    ]
  },
  "jsonpp": {}
}
```
### Installed Packages

``` coffee
# User
atom-pair, v0.37.0
change-case, v0.5.1
emmet, v2.3.4
javascript-snippets, v1.0.0
jshint, v1.2.0
jsonpp, v0.0.6
react, v0.9.10
rspec-snippets, v0.4.0

# Dev
No dev packages
```

**Comment by swenson** [comment]
Call me crazy, but that's not JSON?

I'm just using the builtin JavaScript JSON tools, and it looks like they don't behave well on non-JSON input.

**Comment by enricribas** [comment]
so sorry, yes, you're right. I copied and pasted from ruby. Probably still shouldn't crash though?

**Comment by swenson** [comment]
Agreed that it shouldn't crash. I'll see about adding some warning instead on invalid input.
